language: python
matrix:
  include:
    - os: linux
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'gcc-5']
      env:
        - CXX='g++-5'
        - CC='gcc-5'
      python: 2.7
    - os: linux
      compiler: g++
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'gcc-5']
      env:
        - CXX='g++-5'
        - CC='gcc-5'
      python: 3.6
env:
  global:
    - PIPENV_VENV_IN_PROJECT=1
    - PIPENV_IGNORE_VIRTUALENVS=1
# command to install dependencies
install: make setup
# command to run tests
script:
    - make test
